services:
  prod:
    tty: true
    build:
      context: ../..
      dockerfile: docker/prod/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    command: bun start
