# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# Biome is a performant formatter and linter for JavaScript, TypeScript,
# JSX, and JSON that is drop-in compatible with your existing tools.
# More details at https://biomejs.dev/


name: Biome Code Analysis

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  linter:
    name: Ensure the code format on the changed files
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
      - name: Checkout code
        uses: actions/checkout@v4

      # - https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Install Biome
        run: curl -fsSL https://bun.sh/install | sh

      - name: Verify all files
        run: |
          REMOTE_NAME=origin
          echo "Base ref: $GITHUB_BASE_REF"
          echo "Head ref: $GITHUB_HEAD_REF"
          echo "Fetching branch: $GITHUB_BASE_REF"
          git fetch origin $GITHUB_BASE_REF
          echo "Fetching branch: $GITHUB_HEAD_REF"
          git fetch origin $GITHUB_HEAD_REF
          echo "Listing branches"
          git branch -a
          # echo "Getting diff files ignoring deleted and getting the changed or renamed files"
          # CHANGED_FILES=$(git diff --name-status --diff-filter d ${REMOTE_NAME}/${GITHUB_BASE_REF}..${REMOTE_NAME}/${GITHUB_HEAD_REF} | awk '{print $NF}' | grep -E '.*\.[jt]sx?$' || echo "false")
          # if [ $CHANGED_FILES = "false" ]; then
          #   echo "No changed files found with the extension .js, .jsx, .ts or .tsx"
          #   exit 0
          # fi
          # echo "Changed files:"
          # echo "${CHANGED_FILES}"
          git checkout $GITHUB_HEAD_REF
          echo "Installing dependencies"
          bun install
          echo "Running biome on all files"
          bun format
